macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-xcode:14.3

env:
  CIRRUS_CLONE_DEPTH: 1

build_task:
  brew_script: brew install sdl2 openal-soft sdl2_mixer libpng libvorbis openssh

  cmake_script:
    # FindOpenAL prefers the framework version by default ... which deprecated OpenAL
    - openal="-DOPENAL_INCLUDE_DIR=/usr/local/opt/openal-soft/include/AL -DOPENAL_LIBRARY=/usr/local/opt/openal-soft/lib/libopenal.dylib"
    - mkdir build && cd build
    - export OPENALDIR="/usr/local/opt/openal-soft/"
    - cmake -DCMAKE_INSTALL_PREFIX=iprefix $openal -DCMAKE_FIND_FRAMEWORK=LAST -DUSE_OPENAL=off ..

  build_script:
    - cd build
    - make
    - # try to only run on tag pushes
    - if grep -q '^v[01]\.[0-9].[0-9]' <<< "${CIRRUS_TAG}"; then make fetch-demo-data; fi
    - make install

  test_script:
    - script: true # noop, try real testing on this platform later

  pack_artifacts:
    - path: /Applications/GemRB.app # unfortunately we can't set the resulting name dynamically

publish_task:
  only_if: $CIRRUS_BRANCH == 'master' && $CIRRUS_REPO_OWNER == 'gemrb'
  env:
    SSHKEY: ENCRYPTED[!c6a24980159e845aad3a28f4e25f7c75eab76e7e1c58a1f0e700dfa582f178d4e14856ca70b6802d3aa1a592283f3062!]

  send_script:
    - # generate filename
    - # there are no tags, so improvise
    - v2=$CIRRUS_CHANGE_IN_REPO
    - if [[ -n CIRRUS_TAG ]]; then v2=$CIRRUS_TAG; fi
    - version=$({ date +%F; echo $v2; } | tr -d '\n') || exit 14
    - filepath="Apple/ARM64/gemrb-$version.zip"
    - # unpack ssh key
    - echo $SSHKEY > testing/id_travissfbot.av
    - # down & upload
    - wget https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/build/pack.zip
    - scp -v -oStrictHostKeyChecking=no -i testing/id_travissfbot.av pack.zip gemrb-travisbot@frs.sourceforge.net:/home/frs/project/gemrb/botbins/$filepath
