macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-xcode:14.3

env:
  CIRRUS_CLONE_DEPTH: 1
  SSHKEY: ENCRYPTED[!c6a24980159e845aad3a28f4e25f7c75eab76e7e1c58a1f0e700dfa582f178d4e14856ca70b6802d3aa1a592283f3062!]

build_task:
  brew_script: brew install sdl2 openal-soft sdl2_mixer libpng libvorbis openssh

  cmake_script:
    # FindOpenAL prefers the framework version by default ... which deprecated OpenAL
    - openal="-DOPENAL_INCLUDE_DIR=/usr/local/opt/openal-soft/include/AL -DOPENAL_LIBRARY=/usr/local/opt/openal-soft/lib/libopenal.dylib"
    - mkdir build && cd build
    - export OPENALDIR="/usr/local/opt/openal-soft/"
    - cmake -DCMAKE_INSTALL_PREFIX=iprefix -DBIN_DIR="$CIRRUS_WORKING_DIR" $openal -DCMAKE_FIND_FRAMEWORK=LAST -DUSE_OPENAL=off ..

  build_script:
    - cd build
    - make
    - # try to only run on tag pushes
    - if grep -q '^v[01]\.[0-9].[0-9]' <<< "${CIRRUS_TAG}"; then make fetch-demo-data; fi
    - make install

  test_script:
    - true # noop, try real testing on this platform later

  publish_script:
    - if [[ $CIRRUS_BRANCH != 'master' || $CIRRUS_REPO_OWNER != 'gemrb' ]]; then exit 0; fi
    - # generate filename
    - # there are no tags, so improvise
    - echo $CIRRUS_WORKING_DIR; ls $CIRRUS_WORKING_DIR
    - v2=$CIRRUS_CHANGE_IN_REPO
    - if [[ -n CIRRUS_TAG ]]; then v2=$CIRRUS_TAG; fi
    - version=$({ date +%F; echo $v2; } | tr -d '\n') || exit 14
    - file="gemrb-$version.tar.bz2"
    - # pack
    - tarPath="$CIRRUS_WORKING_DIR/GemRB.app"
    - tar cjf "$file" "$tarPath"
    - # unpack ssh key
    - echo $SSHKEY > testing/id_travissfbot.av
    - chmod 600 testing/id_travissfbot.av
    - # upload
    - filepath="Apple/ARM64/$file"
    - scp -v -oStrictHostKeyChecking=no -i testing/id_travissfbot.av "$file" gemrb-travisbot@frs.sourceforge.net:/home/frs/project/gemrb/botbins/$filepath
