# TODO: deploy to bintray, sdl_mixer is not found for linux
language: cpp

compiler:
  - clang
  - gcc

sudo: false

addons:
  apt:
    packages:
    - cmake
    - libpython2.7
    - zlib1g
    - zlib1g-dev
    - libsdl1.2debian
    - libsdl1.2-dev
    - libopenal1
    - libopenal-dev
    - libsdl-mixer1.2
    - libsdl-mixer1.2-dev
    - libfreetype6
    - libfreetype6-dev
    - libvlc5
    - libvlc-dev
    - libvlccore5
    - libvlccore-dev
    - libpng12-0
    - libpng12-dev
    - libvorbis0a
    - libvorbis-dev
    - python-dev

before_install:
# homebrew missing: vlc
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install sdl python openal-soft freetype sdl_mixer libpng libvorbis; fi

before_script:
  - cmake --version # too old for MODULE, but only on the linux host
  - if [ $TRAVIS_OS_NAME != osx ]; then sed -i 's,\(FIND_PACKAGE.*\) MODULE,\1,' CMakeLists.txt; fi

script:
  - mkdir build && cd build
  - cmake . && make
  - gemrb/gemrb -c ../gemrb/GemRB.cfg.noinstall.sample # minimal test

notifications:
  email:
    on_success: never
    on_failure: change
  irc:
    channels:
      -  "irc.freenode.org#gemrb"
    on_success: never
    on_failure: change

os:
  - linux
  - osx
