# TODO: sdl_mixer is not found for linux, vlc for mac
# TODO: run the minimal test also from the installed gemrb
language: cpp

compiler:
  - clang
  - gcc

sudo: false

addons:
  apt:
    packages:
    - cmake
    - libpython2.7
    - zlib1g
    - zlib1g-dev
    - libsdl1.2debian
    - libsdl1.2-dev
    - libopenal1
    - libopenal-dev
    - libsdl-mixer1.2
    - libsdl-mixer1.2-dev
    - libfreetype6
    - libfreetype6-dev
    - libvlc5
    - libvlc-dev
    - libvlccore5
    - libvlccore-dev
    - libpng12-0
    - libpng12-dev
    - libvorbis0a
    - libvorbis-dev
    - openssh-client
    - python-dev
  ssh_known_hosts: frs.sourceforge.net

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install sdl python openal-soft freetype sdl_mixer libpng libvorbis; fi
  - openssl aes-256-cbc -K $encrypted_798b15af9f34_key -iv $encrypted_798b15af9f34_iv -in testing/id_travissfbot.enc -out id_travissfbot -d
  - chmod 0600 id_travissfbot

before_script:
  - cmake --version # too old for MODULE, but only on the linux host
  - if [ $TRAVIS_OS_NAME != osx ]; then sed -i 's,\(FIND_PACKAGE.*\) MODULE,\1,' CMakeLists.txt; fi

script:
  - mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=iprefix -DSTATIC_LINK=1 ..
  - make
  - if [ $TRAVIS_OS_NAME != osx ]; then gemrb/gemrb -c ../gemrb/GemRB.cfg.noinstall.sample; fi # minimal test
  - make install

deploy:
  skip_cleanup: true
  provider: script
  script: ../testing/travis-deploy.sh
  on:
    branch: master
    condition: $CC == gcc

notifications:
  email:
    on_success: never
    on_failure: change
  irc:
    channels:
      -  "irc.freenode.org#gemrb"
    on_success: never
    on_failure: change

os:
  - linux
  - osx
