# TODO: sdl_mixer is not found for linux, vlc for mac
# TODO: run the minimal test also from the installed gemrb
language: cpp

dist: bionic
compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - cmake
    - libpython2.7
    - zlib1g
    - zlib1g-dev
    - libsdl1.2debian
    - libsdl1.2-dev
    - libopenal1
    - libopenal-dev
    - libsdl-mixer1.2
    - libsdl-mixer1.2-dev
    - libfreetype6
    - libfreetype6-dev
    - libvlc-dev
    - libvlccore-dev
    - libpng16-16
    - libpng-dev
    - libvorbis0a
    - libvorbis-dev
    - openssh-client
    - python-dev
    - g++-6
    
    # not needed for building
    - gdb

  ssh_known_hosts: frs.sourceforge.net

before_install:
  - if [[ $CC == gcc ]]; then CC=gcc-6 && CXX=g++-6; fi
  - export CC CXX
  - touch id_travissfbot
  - if [[ $TRAVIS_SECURE_ENV_VARS == "true" ]]; then openssl aes-256-cbc -K $encrypted_d3cf1349d561_key -iv $encrypted_d3cf1349d561_iv -in testing/id_travissfbot.enc -out id_travissfbot -d; fi
  - chmod 0600 id_travissfbot

before_script:
  - cmake --version
  
after_failure:
  - for i in $(find ./ -maxdepth 2 -name 'core*' -print); do gdb gemrb/gemrb core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done; # find core file

script:
  - |
    mkdir build && cd build &&
    static="-DSTATIC_LINK=1 -DLAYOUT=home" &&
    cmake -DCMAKE_INSTALL_PREFIX=iprefix $static .. &&
    make &&
    sed -i '1 a \ AudioDriver = none' ../gemrb/GemRB.cfg.noinstall.sample &&
    gemrb/gemrb -c ../gemrb/GemRB.cfg.noinstall.sample &&
    make install

deploy:
  provider: script
  edge: true
  script: ../testing/travis-deploy.sh
  on:
    branch: master
    condition: $CC == clang

notifications:
  email:
    on_success: never
    on_failure: change
  irc:
    channels:
      -  "irc.freenode.org#gemrb"
    on_success: never
    on_failure: change

os:
  - linux
