name: Builders

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, subviews ]

jobs:
  macos:
    name: MacOS build
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Homebrew
      run: |
        brew install sdl openal-soft sdl_mixer libpng libvorbis

    - name: Set up build
      run: |
        # FindOpenAL prefers the framework version by default ... which deprecated OpenAL
        openal="-DOPENAL_INCLUDE_DIR=/usr/local/opt/openal-soft/include -DOPENAL_LIBRARY=/usr/local/opt/openal-soft/lib"
        mkdir build && cd build &&
        cmake --version &&
        cmake -DCMAKE_INSTALL_PREFIX=iprefix $openal ..

    - name: Build
      run: |
        cd build &&
        make &&
        make install

    - name: Set up SSH
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1
      if: ${{ github.event_name == 'push' }}
      with:
        ssh-private-key: ${{ secrets.SSH_SF_PRIVATE_KEY }}
        ssh-host: frs.sourceforge.net

    - name: Upload
      if: ${{ github.event_name == 'push' }}
      env:
        OS: ${{ runner.os }}
      run: |
        # NOTE: only do it on clang builds if we ever add more compilers
        if [[ $OS == macOS ]]; then
          filepath=Apple/OSX
          tarpath=/Applications/GemRB.app
        elif [[ $OS == Linux ]]; then
          filepath=Linux
          tarpath=iprefix
        else
          echo "Unknown platform, exiting!"
          exit 13
        fi

        # there are no tags, so improvise
        version=$({ date +%F; git describe --always; } | tr -d '\n') || exit 14
        file=gemrb-$version.tar.bz2
        tar cjf $file $tarpath || exit 15

        filepath="$filepath/$file"
        scp $file \
        gemrb-travisbot@frs.sourceforge.net:/home/frs/project/gemrb/Buildbot\\\ Binaries/$filepath
