name: Builders

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, subviews ]

jobs:
  macos:
    name: MacOS build
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Homebrew
      run: |
        brew install sdl openal-soft sdl_mixer libpng libvorbis

    - name: Set up build
      run: |
        # FindOpenAL prefers the framework version by default ... which deprecated OpenAL
        openal="-DOPENAL_INCLUDE_DIR=/usr/local/opt/openal-soft/include -DOPENAL_LIBRARY=/usr/local/opt/openal-soft/lib"
        mkdir build && cd build &&
        cmake --version &&
        cmake -DCMAKE_INSTALL_PREFIX=iprefix $openal ..

    - name: Build
      run: |
        # cd build &&
        make &&
        make install
